### ISSUE TITLE
Iteration Plan for v2.18.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1037]
This plan captures our work in May. This is a 3-week iteration. We will ship in mid-May. 

# Plan Items
  
Legend of annotations:
  
|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |
  
Below is a summary of the top-level plan items.

## Editor

- [x] untitled 文件仅支持 type 为 code 的打开方式 [#1027](https://api.github.com/repos/opensumi/core/issues/1027). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 修复部分文件，如 `~/.sumi/settings.json` 文件打开后缺少面包屑组件的问题 [#1013](https://api.github.com/repos/opensumi/core/issues/1013). [@iamxukai](https://api.github.com/users/iamxukai)
- [x] 支持通过 "打开方式..." 菜单来打开文件，并允许设置某类文件的默认打开方式 [#987](https://api.github.com/repos/opensumi/core/issues/987). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 编辑器右上角区域支持切换文件打开方式 [#973](https://api.github.com/repos/opensumi/core/issues/973). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 移除编辑器内置的 Markdown 文件预览视图 [#968](https://api.github.com/repos/opensumi/core/issues/968). [@moreJs](https://api.github.com/users/moreJs)
- [x] 编辑器内联界面文件兼容图标主题，与文件树上图标保持一致 [#963](https://api.github.com/repos/opensumi/core/issues/963). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] 支持 workbench.editorAssociations 配置项 [#957](https://api.github.com/repos/opensumi/core/issues/957). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 修复格式化一直显示选择框的问题 [#934](https://api.github.com/repos/opensumi/core/issues/934). [@Aaaaash](https://api.github.com/users/Aaaaash)

## Extension Manager

- [x] 💪 优化插件市场面板样式，同时修复插件安装状态显示问题 [#1005](https://api.github.com/repos/opensumi/core/issues/1005). [@songhn233](https://api.github.com/users/songhn233)
    
## FileTree

- [x] 修复文件树二次进入状态恢复问题 [#983](https://api.github.com/repos/opensumi/core/issues/983). [@erha19](https://api.github.com/users/erha19)
- [x] 💪 优化文件树渲染性能，增强高并发渲染场景下的稳定性及响应速度 [#866](https://api.github.com/repos/opensumi/core/issues/866), [#916](https://api.github.com/repos/opensumi/core/issues/916). [@erha19](https://api.github.com/users/erha19)

## Debug

- [x] 💪 👨🏻‍💻 适配 VS Code JavaScript Debugger 插件 1.67.1 版本 [#396](https://api.github.com/repos/opensumi/core/issues/396). [@erha19](https://api.github.com/users/erha19)
- [x] 修复 Windows 下对于工作区路径等调试变量的支持 [#962](https://api.github.com/repos/opensumi/core/issues/962). [@erha19](https://api.github.com/users/erha19)
- [x] RPCProtocol 支持 ArrayBuffer 消息类型 [#945](https://api.github.com/repos/opensumi/core/issues/945). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 修复 DebugAdapterTracker 的 message 类型错误问题 [#939](https://api.github.com/repos/opensumi/core/issues/939). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 适配调试进程中对于 `customRequest` 请求的返回结果，与 VS Code 表现对齐 [#931](https://api.github.com/repos/opensumi/core/issues/931). [@kidswong999](https://api.github.com/users/kidswong999)
- [ ] 修复调试监听面板中的 `ThrottledDelayer Cancel` 报错信息 [#1036](https://api.github.com/repos/opensumi/core/issues/1036). [@Ricbet](https://api.github.com/users/Ricbet)

## Terminal

- [ ] 👨🏻‍💻 实验性: 添加/适配 终端LocalEcho功能 #1028. @life2015
- [x] 💪 👨🏻‍💻 支持单/多容器架构下的终端重连能力 #713. @life2015 
- [x] Terminal 标题名称默认按传入值进行展示 [#924](https://api.github.com/repos/opensumi/core/issues/924). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] 优化新建终端的交互，新建按钮跟随 Tab 位置移动 [#919](https://api.github.com/repos/opensumi/core/issues/919). [@hacke2](https://api.github.com/users/hacke2)

## Preference

- [x] 💪 在传入默认配置值的情况下正确处理设置面板默认值展示 [#1023](https://api.github.com/repos/opensumi/core/issues/1023). [@erha19](https://api.github.com/users/erha19)

## QuickOpen

- [ ] 💪 支持 VSCode 插件 API 1.63.2 中的 QuickOpen 相关 API #843. [@yantze](https://api.github.com/users/yantze)

## Refactor

- [ ] 🏃 👨🏻‍💻 支持 React 18 [#970](https://api.github.com/repos/opensumi/core/issues/970). [@Aaaaash](https://api.github.com/users/Aaaaash
- [ ] 简化框架依赖，移除冗余依赖 [#979](https://api.github.com/repos/opensumi/core/issues/979). [@bytemain](https://api.github.com/users/bytemain)
- [x] 💪 整理框架 `utils` 工具，抽离 `@opensumi/ide-utils` 以获得更好的依赖结构，解决循环引用问题 [#784](https://api.github.com/repos/opensumi/core/issues/784). [@erha19](https://api.github.com/users/erha19)
- [x] 将commander改为yargs [#1017](https://api.github.com/repos/opensumi/core/issues/1017). [@dqhl76](https://api.github.com/users/dqhl76)
- [x] 修复 Windows 环境下，Electron 客户端顶部 Header 高度异常问题 [#995](https://api.github.com/repos/opensumi/core/issues/995). [@yantze](https://api.github.com/users/yantze)
- [x] remove @opensumi/ide-core-common dependence from utils [#958](https://api.github.com/repos/opensumi/core/issues/958). [@erha19](https://api.github.com/users/erha19)
- [x] 替换框架依赖的 `shortid` 为性能更好的 `nanoid` [#923](https://api.github.com/repos/opensumi/core/issues/923). [@dqhl76](https://api.github.com/users/dqhl76)

## Electron

- [x] 兼容 Windows 环境下对图标、worker.host.js 等资源的读取 [#1019](https://api.github.com/repos/opensumi/core/issues/1019). [@yantze](https://api.github.com/users/yantze)
 
## Style Change

- [x] 添加全局文字大小变量 [#928](https://api.github.com/repos/opensumi/core/issues/928). [@Aaaaash](https://api.github.com/users/Aaaaash)

## Others 

- [x] lock vscode-languageserver-protocol dependence version [#1007](https://api.github.com/repos/opensumi/core/issues/1007). [@erha19](https://api.github.com/users/erha19)
- [x] attach 后端或 host 时跳过  node_internals [#944](https://api.github.com/repos/opensumi/core/issues/944). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] Update jest `collectCoverageFrom` config [#914](https://api.github.com/repos/opensumi/core/issues/914). [@bytemain](https://api.github.com/users/bytemain)
- [x] use jsdom enviroments for browser and node enviroments for node [#901](https://api.github.com/repos/opensumi/core/issues/901). [@bytemain](https://api.github.com/users/bytemain)

Release Notes 见：[release-notes/v2.18.md](https://github.com/opensumi/doc/blob/main/release-notes/v2.18.md).

**Comment by erha19** [comment]
done [v2.18.0](https://github.com/opensumi/core/releases/tag/v2.18.0).
