### ISSUE TITLE
Iteration Plan for v2.19.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1153]
This plan captures our work in June. This is a 3-week iteration. We will ship in end-June. 

# Plan Items
  
Legend of annotations:
  
|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |
  
Below is a summary of the top-level plan items.

## Terminal

- [x] 💪 终端输入实现实验性的 LocalEcho 功能 #1028 by @life2015 
- [ ] 修复终端打开的外部文件无法同步外部更新的问题 #1089

## File Service

- [ ] 文件服务在响应层级超过 5 层的文件事件存在类型上的异常 #915

## Debug

- [ ] debug memory variable support view as binary #1035 by @Ricbet 

## Extension API

- [ ] update openTextDocument API, support more options  #1126 by @AhkunTa 

## QuickPick

- [x] command quick open support alias #1134 by @bytemain 

## Refactor

- [ ] 💪 support React 18 #970 by @Aaaaash 
- [x]  简化模块依赖 #1102 by @bytemain 
- [ ] 合并 `search` 和 `file-search` 模块 #881

## Performance Improvements

- [x] 💪 通过优化 Storage 存储流程的方式优化二次打开加载速度 #1205

## Style Change

- [ ] 修复框架渲染骨架图样式问题 #902

## Others

- [ ] ide-overlay 的 IDialogService 的 dialog 支持自定义属性 #1057
- [ ] 适配 eamodio.gitlens 12.0.6 版本 #903
- [ ] get layout maxSize property error #1154 by @bk1012 
- [ ] #1254 @Ricbet
