### ISSUE TITLE
Iteration Plan for v2.20.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1509]
This plan captures our work in July & August. This is a 4-week iteration. We will ship in mid-August.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Editor

- [ ] 💪 🏃升级 Monaco 编辑器至 0.34.0+ 版本 #1493. @Aaaaash @life2015 @erha19 
- [x] 优化编辑器文件树及 tab 点击时的聚焦行为 [#1448](https://github.com/opensumi/core/pull/1448). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] 💪 修复 gitlens 左侧 originaleditor 无法展示 blame 的问题 [#1452](https://github.com/opensumi/core/pull/1452). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] improve editor tab text style [#1500](https://github.com/opensumi/core/pull/1500). [@erha19](https://api.github.com/users/erha19)
- [x]  #1455. @erha19 

## Opened Editor

- [ ] #1316. @erha19 

## FileTree

- [x]  file missing while refreshing on sub files [#1441](https://github.com/opensumi/core/pull/1441). [@erha19](https://api.github.com/users/erha19)
- [x] 优化编辑器打开后滚动到屏幕中间的行为 [#1483](https://github.com/opensumi/core/pull/1483). [@Aaaaash](https://api.github.com/users/Aaaaash)

## FileService

- [x] 替换 NSFW 为性能及准确性更好的 @parcel/watcher  #1437 .  @erha19 
- [x] supported VS Code 1.69.0 FileEvent API [#1447](https://github.com/opensumi/core/pull/1447). [@Aaaaash](https://api.github.com/users/Aaaaash)

## Debug

- [x] 修复编辑器 Tab 自动换行样式问题，同时优化调试工具栏位置 [#1478](https://github.com/opensumi/core/pull/1478). [@erha19](https://api.github.com/users/erha19)
- [x] 优化调试变量展示的节点顺序 [#1496](https://github.com/opensumi/core/pull/1496). [@erha19](https://api.github.com/users/erha19)

## Webview

- [ ] #1476.

## Search

- [x] 取消搜索面板自动设置来自编辑器的选中文本 [#1492](https://github.com/opensumi/core/pull/1492). [@yantze](https://api.github.com/users/yantze)
- [x] 修复搜索中包含已经删除的文件内容的问题 [#1495](https://github.com/opensumi/core/pull/1495). [@yantze](https://api.github.com/users/yantze)

## Keymaps

- [x] 修复快捷键面板无法正常关闭问题 [#1440](https://github.com/opensumi/core/pull/1440). @erha19 
- [x] 修复快捷键面板修改快捷键可能受外部修改影响问题 [#1480](https://github.com/opensumi/core/pull/1480). [@erha19](https://api.github.com/users/erha19)

## Extension API

- [x] improve Gitlens 12+ welcome page style [#1451](https://github.com/opensumi/core/pull/1451). [@erha19](https://api.github.com/users/erha19)
- [x] improve extension TreeView items order [#1464](https://github.com/opensumi/core/pull/1464). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] remove default TreeView's icon height [#1474](https://github.com/opensumi/core/pull/1474). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] 支持 editor/title/run 贡献点 [#1490](https://github.com/opensumi/core/pull/1490). [@Ricbet](https://api.github.com/users/Ricbet)
- [x] 去除可能导致加载异常的 treeview 缓存 [#1507](https://github.com/opensumi/core/pull/1507). [@Aaaaash](https://api.github.com/users/Aaaaash)

## QuickOpen

- [x] 💪 提供 QuickOpen 通用的 modifier 按键监听方法 [#1458](https://github.com/opensumi/core/pull/1458). [@yantze](https://api.github.com/users/yantze)

## Refactor

- [ ] 💪 🏃 #592. @erha19 
- [ ] 💪  🏃#79. @erha19 
- [x] 💪 添加 `@opensumi/playwright` 用于支持所有基于 opensumi 搭建的 IDE 产品 E2E 测试 #1263. @erha19  
- [ ] #1299 . @songhn233 

## Layout

- [x] 修复手风琴视图标题更新失败的问题 [#1471](https://github.com/opensumi/core/pull/1471). [@Aaaaash](https://api.github.com/users/Aaaaash)

## Style Change

- [x] 优化 codicon 默认样式 [#1449](https://github.com/opensumi/core/pull/1449). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] improve ghost and secondary button fallback style [#1465](https://github.com/opensumi/core/pull/1465). [@erha19](https://api.github.com/users/erha19)
- [x]  improve ICON style [#1466](https://github.com/opensumi/core/pull/1466). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] 改变选中文本后的颜色为默认值 [#1487](https://github.com/opensumi/core/pull/1487). [@yantze](https://api.github.com/users/yantze)
- [x] #1506. @erha19 

## Others

- [x]  supported custom icon scheme [#1498](https://github.com/opensumi/core/pull/1498). [@hacke2](https://api.github.com/users/hacke2)
- [x] 修复 withProgress 意外的抛出异常 [#1501](https://github.com/opensumi/core/pull/1501). [@Aaaaash](https://api.github.com/users/Aaaaash)
- [x] support closeable option on progress api #1508 . @erha19

**Comment by erha19** [comment]
Done [v2.20.0](https://github.com/opensumi/core/releases/tag/v2.20.0).
