### ISSUE TITLE
Iteration Plan for v2.21.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1777]
This plan captures our work between September and October. This is a 4-week iteration. We will ship in mid-October.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Editor

- [x] 修复 releaseHints 返回值错误的问题 [#1754](https://github.com/opensumi/core/pull/1754). [@Aaaaash](https://github.com/Aaaaash)
- [x] 更新语法注册逻辑，解决新版本编辑器无法正确匹配括号的问题 [#1752](https://github.com/opensumi/core/pull/1752). [@Aaaaash](https://github.com/Aaaaash)
- [x] add editor copyPath contextMenu [#1745](https://github.com/opensumi/core/pull/1745). [@erha19](https://github.com/erha19)
- [x] limit editor tab subname length [#1739](https://github.com/opensumi/core/pull/1739). [@erha19](https://github.com/erha19)
- [x] improve tabs and breadcrumb icon style [#1716](https://github.com/opensumi/core/pull/1716). [@erha19](https://github.com/erha19)
- [x] fit editor hover content widget z-index [#1676](https://github.com/opensumi/core/pull/1676). [@erha19](https://github.com/erha19)
- [x] save task should be resolve after canceled [#1664](https://github.com/opensumi/core/pull/1664). [@erha19](https://github.com/erha19)
- [x] support navigate editor history by mouse 3/4 [#1663](https://github.com/opensumi/core/pull/1663). [@erha19](https://github.com/erha19)
- [x] update some editor commands description [#1661](https://github.com/opensumi/core/pull/1661). [@bytemain](https://github.com/bytemain)
- [x] support move editor tabs over the tabbar #1671. @erha19
- [x] 💪 support multi-person collaborative editing #1274. @situ2001

## SCM

- [x] 修复 SCM 的"在侧边栏打开" 失效的问题 [#1682](https://github.com/opensumi/core/pull/1682). [@Ricbet](https://github.com/Ricbet)

## Search

- [x] arrow up key doesn't trigger search #1774. @bytemain

## FileTree

- [x] 修复文件树在提示错误信息时失焦后不消失的问题 [#1715](https://github.com/opensumi/core/pull/1715). [@Ricbet](https://github.com/Ricbet)
- [x]  💪  支持跨窗口文件复制-粘贴能力 Implementation of cross-end and cross-window file system service #1594. @songhn233 

## Debug

- [x] 💪 auto-close debug terminal after finished or closed [#1652](https://github.com/opensumi/core/pull/1652). [@erha19](https://github.com/erha19)
- [x] 修复调试（终端类型）后编辑器语法提示失效问题 #1771. @Ricbet

## Terminal

- [x] 改进终端按钮上的悬浮提示 [#1705](https://github.com/opensumi/core/pull/1705). [@Ricbet](https://github.com/Ricbet)
- [x] 💪 terminal use webgl renderer [#1653](https://github.com/opensumi/core/pull/1653). [@Aaaaash](https://github.com/Aaaaash)

## Preference

- [x] User setting.json 配置文件支持可枚举项的下拉框选择 [#1722](https://github.com/opensumi/core/pull/1722). [@Ricbet](https://github.com/Ricbet)

## Theme

- [x] support high contrast light theme [#1728](https://github.com/opensumi/core/pull/1728). [@AhkunTa](https://github.com/AhkunTa)

## Extension API

- [x] Extension Treeview 支持通过 FileDecorationProvider 注册装饰块 [#1734](https://github.com/opensumi/core/pull/1734). [@Aaaaash](https://github.com/Aaaaash)
- [x] upgrade VS Code engine to 1.63.2 [#1724](https://github.com/opensumi/core/pull/1724). [@hacke2](https://github.com/hacke2)
- [x] implement quickpick kind api [#1673](https://github.com/opensumi/core/pull/1673). [@hacke2](https://github.com/hacke2)
- [x]  showCollapseAll prop invalid [#1660](https://github.com/opensumi/core/pull/1660). [@yantze](https://github.com/yantze)
- [x] 💪 support TreeView Drag API #1764. @erha19
- [x] 💪 support Git actionButton and improve style #1702. @erha19
- [x] 💪 support description and message on extension treeview   #1737. @Aaaaash 

## QuickOpen

- [x] quickOpen 支持 codicons 图标渲染 [#1704](https://github.com/opensumi/core/pull/1704). [@Ricbet](https://github.com/Ricbet)

## Toolbar

- [x] show toolbar button id in Toolbar Customize [#1725](https://github.com/opensumi/core/pull/1725). [@bytemain](https://github.com/bytemain)
- [ ] support toolbar dropdown-button contribute #1753. @hacke2

## Performance Improvements

- [ ] 💪 优化部分启动逻辑 #1772. @Aaaaash

## Style Change

- [x] remove useless sencondaryButtonBorder style [#1755](https://github.com/opensumi/core/pull/1755). [@erha19](https://github.com/erha19)
- [x] improve selectionBackground and GhostButton style [#1735](https://github.com/opensumi/core/pull/1735). [@erha19](https://github.com/erha19)
- [x] improve select option style in light mode [#1727](https://github.com/opensumi/core/pull/1727). [@hacke2](https://github.com/hacke2)
- [x] improve select component and global color tokens style [#1683](https://github.com/opensumi/core/pull/1683). [@erha19](https://github.com/erha19)
- [x] improve terminal and editor tabs style [#1665](https://github.com/opensumi/core/pull/1665). [@erha19](https://github.com/erha19)
- [x] improve file dialog tree style #1770. @erha19

## Electron

- [x] 修复没有打开文件的情况标题栏信息展示异常 [#1763](https://github.com/opensumi/core/pull/1763). [@yantze](https://github.com/yantze)
- [x] 支持自定义 electron 的 header 组件 [#1730](https://github.com/opensumi/core/pull/1730). [@yantze](https://github.com/yantze)
- [x] 修复 Electron HeaderBar 的拖动区域狭窄问题 [#1714](https://github.com/opensumi/core/pull/1714). [@yantze](https://github.com/yantze)
- [x] Allow set partition value to webview element by PlainWebviewHandle [#1657](https://github.com/opensumi/core/pull/1657). [@bytemain](https://github.com/bytemain)
- [x] support macos native dirty indicator #1773. @bytemain
- [x] support set window title #1767. @bytemain

## E2E Test

- [x] 增加 "文件树自动定位并选择" 的 e2e 测试 [#1765](https://github.com/opensumi/core/pull/1765). [@Ricbet](https://github.com/Ricbet)
- [x] 增加 “关闭全部” 的 e2e 测试 [#1758](https://github.com/opensumi/core/pull/1758). [@Ricbet](https://github.com/Ricbet)
- [x] improve e2e test stability and  add terminal test case [#1710](https://github.com/opensumi/core/pull/1710). [@erha19](https://github.com/erha19)
- [x] add new file/folder from toolbar test #1775. @erha19

## Others

- [x] fix uncontrol notification style and duration [#1744](https://github.com/opensumi/core/pull/1744). [@erha19](https://github.com/erha19)
- [x] Remove yargs dependency [#1726](https://github.com/opensumi/core/pull/1726). [@bytemain](https://github.com/bytemain)
- [x] change statusbar view when tooltip updated [#1712](https://github.com/opensumi/core/pull/1712). [@hacke2](https://github.com/hacke2)
- [x] only handle scheme file on collaborative mode [#1709](https://github.com/opensumi/core/pull/1709). [@situ2001](https://github.com/situ2001)
- [x] BoxPanel generate child with className [#1706](https://github.com/opensumi/core/pull/1706). [@bytemain](https://github.com/bytemain)
- [x] 增加了菜单 View/Terminal/Go 中的命令 [#1701](https://github.com/opensumi/core/pull/1701). [@bytemain](https://github.com/bytemain)
- [ ] using browser version jsonrpc client to connect server #1584. @yantze

**Comment by erha19** [comment]
done https://github.com/opensumi/core/releases/tag/v2.21.0.
