### ISSUE TITLE
Iteration Plan for v2.22.0 

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1970]
This plan captures our work in November. This is maybe a 4-week iteration. We will ship in December.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Performance Improvements

- [x] update prefered options after textModel is created [#1947](https://github.com/opensumi/core/pull/1947). [@Aaaaash](https://github.com/Aaaaash)
- [x] lazy load language configuration [#1945](https://github.com/opensumi/core/pull/1945). [@Aaaaash](https://github.com/Aaaaash)
- [x] do not active disabled extension [#1931](https://github.com/opensumi/core/pull/1931). [@Aaaaash](https://github.com/Aaaaash)

## FileService

- [x] add parcel watcher retry delay [#1932](https://github.com/opensumi/core/pull/1932). [@life2015](https://github.com/life2015)
- [x] update unsupported watch exclude glob [#1926](https://github.com/opensumi/core/pull/1926). [@erha19](https://github.com/erha19)
- [x] make watcher can be disposed [#1925](https://github.com/opensumi/core/pull/1925). [@bytemain](https://github.com/bytemain)
- [x] register code snippets timing [#1920](https://github.com/opensumi/core/pull/1920). [@Aaaaash](https://github.com/Aaaaash)
- [x] parcel watcher version bump [#1908](https://github.com/opensumi/core/pull/1908). [@life2015](https://github.com/life2015)

## Editor

- [x] support mousewheel on editor tabs [#1927](https://github.com/opensumi/core/pull/1927). [@erha19](https://github.com/erha19)
- [x] 修复 peekView 内获取到错误编辑器实例的问题 [#1893](https://github.com/opensumi/core/pull/1893). [@Aaaaash](https://github.com/Aaaaash)
- [x] 调整 monaco 代码，使代码片段 prefix 属性支持数组 [#1891](https://github.com/opensumi/core/pull/1891). [@shilin8805](https://github.com/shilin8805)

## Search

- [x] make the search references clean up [#1923](https://github.com/opensumi/core/pull/1923). [@yantze](https://github.com/yantze)
- [x] always highlight search results [#1900](https://github.com/opensumi/core/pull/1900). [@erha19](https://github.com/erha19)
- [x] improve file search results order [#1895](https://github.com/opensumi/core/pull/1895). [@erha19](https://github.com/erha19)

## FileTree

- [x] ignore composition start when filetree rename [#1913](https://github.com/opensumi/core/pull/1913). [@erha19](https://github.com/erha19)
- [x] support dblclick when rename file [#1897](https://github.com/opensumi/core/pull/1897). [@erha19](https://github.com/erha19)

## Extension

- [x] 修复 `workspaceContains` activateEvents 不生效的问题 [#1883](https://github.com/opensumi/core/pull/1883). [@Aaaaash](https://github.com/Aaaaash)
- [x] 修复安装/启用插件后没有激活的问题 [#1882](https://github.com/opensumi/core/pull/1882). [@Aaaaash](https://github.com/Aaaaash)

## Refactor

- [x] move lifecycle type definition to common module [#1909](https://github.com/opensumi/core/pull/1909). [@Aaaaash](https://github.com/Aaaaash)

## Style Changes

- [x] keep dialog `message` field's className [#1903](https://github.com/opensumi/core/pull/1903). [@bytemain](https://github.com/bytemain)
- [x] the secondary button click background style [#1890](https://github.com/opensumi/core/pull/1890). [@erha19](https://github.com/erha19)

## Others

- [x] remove all warnings from the console [#1892](https://github.com/opensumi/core/pull/1892). [@erha19](https://github.com/erha19)

## Milestone

Other plans here: [Milestone 2.22](https://github.com/opensumi/core/milestone/7).

**Comment by erha19** [comment]
PreRelease #2131.

**Comment by erha19** [comment]
Done [v2.22.0](https://github.com/opensumi/core/releases/tag/v2.22.0).
