### ISSUE TITLE
[DISSCUSSION] OpenSumi 2022 RoadMap

### ISSUE THREAD

**Issue by erha19** [opensumi/core#315]
After the meeting of our core members in January 2022, we settled on the following actions:

## Features

- [ ] Make Windows URI great again, solve the different environment problems of URI in node and browser Windows. @yantze 
- [ ] Optimize debug console performance,  support showing large debug console messages and so on. @Ricbet 
- [ ] Support copy or paste files across windows, find a new way to copy or paste files across Web or Electron windows. @erha19 
- [ ] Improve code completion with Monaco editor. @Ricbet 
- [ ] Try compatible with Github Copilot @Aaaaash.  @hacke2 
- [ ] The new extension marketplace for OpenSumi. @hacke2 
- [ ] Optimize framework dependency structure. @erha19 
- [ ] Support the new JavaScript Debugger. @erha19 @Ricbet 
- [ ] Support file operation redo and undo. @Ricbet 
- [ ] Support reconnect existing terminal process after the page is refreshed. @life2015 

##. Refactor

- [ ] Replace nsfw with @parcel/watcher @lengthmin  @MMhunter  @erha19 
- [ ] The new Sandbox mode for a browser extension. @Aaaaash 
- [ ] Use @opensumi/ide-components as sumi-browser's components. @erha19 
- [ ] Split a utils module from `@opensumi/ide-core-common` and  `@opensumi/ide-core-components`.  @erha19 

## Docs

- [ ] More OpenSumi modules sample. @hacke2  @Aaaaash @erha19 
- [ ] Our own website `opensumi.com`. @erha19
