### ISSUE TITLE
Iteration Plan for v2.14.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#333]
This plan captures our work in January. This is a 2-week iteration. We will ship in mid-February.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Roadmap

- [ ] 🐚 2022 Roadmap [discussions#316](https://github.com/opensumi/core/discussions/316).

## Editor

- [x] alt/option causes hover to fail on editor view #248. @Ricbet
- [x] fix content may be incorrect while saving a large file problem #183. @Aaaaash
- [x] support `TextDocumentChangeEvent.reason` properties #78. @Aaaaash

## Extension

- [x] add extension overview page download button #306. @yantze
- [x] fix extension configuration contributionPoint parse error #88. @erha19
- [x] add extension marketplace view #50. @Aaaaash

## Debug

- [x] fix DAP message `breakpointLocations` may be repeated more than one time while using the latest `vscode-mock-debug` sample #181 #177. @Ricbet
- [x] fix `debug.removeBreakpoints` API does not work #225. @Ricbet
- [x] support recognized `${env: xxx}` environment variable #81. @Ricbet

## Terminal

- [x] fix the default Terminal behavior in Windows #160. @lengthmin
- [x] shows an error message if Terminal cannot start #159. @lengthmin
- [x] fix Terminal not responding to theme changes #147. @Aaaaash
- [x] support contextMenu on Terminal #182. @Aaaaash

## Components

- [x] support easy-to-use RecycleTree component #93. @erha19

## Storage

- [x] fix Storage module readFile logic #233. @yantze

## Electron

- [x] kill process fails on Windows Electron #221. @yantze
- [x] 🏃 👨🏻‍💻 support remote mode to connect with remote container #310 #311. @yantze @Aaaaash @hacke2 

## API

- [x] support `vscode.env.appHost` API #71. @erha19
- [x] support `Memento.keys` API #70. @erha19
- [x] support `lifecycleManagedByParent` API #64 #43. @Ricbet
- [x] support TerminalOptions.message api #49. @jinboker
- [x] support `TerminalLink` API #85. @yantze
- [x] support `TerminalLink.tooltip` property #77. @yantze
- [x] support `Pseudoterminal.onDidChangeName` API #48. @jinboker
- [ ] 🏃 support `VSCode TerminalProfileProvider` API #34. @lengthmin
- [x] support `TaskGroup.isDefault / TaskGroup.id` property #76. @Aaaaash @ AhkunTa 

## Configurations

- [x] support remote opener on Cloud IDE #266. @Aaaaash
- [x] support hiding left panel tabbar #175. @lengthmin
- [x] support custom `.code-workspace` suffix #82. @erha19

## Refactor

- [ ] 👨🏻‍💻  use @opensumi/ide-components as sumi-browser's components #79. @erha19

## Others

- [x] remove some useless command from Command Palette #166. @Ricbet
- [x] add built-in icons website #145. @Aaaaash
- [x] add OpenSumi electron-built workflows #75. @yantze

## Style Change

- [x] improve editor tab bar icon size #156. @Aaaaash

**Comment by erha19** [comment]
- #350

**Comment by Aaaaash** [comment]
- #390

**Comment by Aaaaash** [comment]
test
