### ISSUE TITLE
Iteration Plan for v2.15.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#433]
This plan captures our work in February. This is a 2-week iteration. We will ship in mid-February.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Roadmap

- [ ] 🐚 2022 Roadmap [discussions#316](https://github.com/opensumi/core/discussions/316).

## FileTree

- [x] 修复文件复选操作后右键删除文件不符合预期问题 #404 . @erha19 
- [x] 修复文件操作时同时选择父目录和子目录时出现异常报错问题  #403 . @erha19 

## Debug

- [x] 当不存在配置情况下启动调试时，隐藏 Debug 欢迎面板并展示断点面板信息 #401 . @Ricbet 
- [ ] 🏃 适配 VS Code JavaScript Debugger 插件 1.62.0 版本 #396. @erha19 
- [x] 🏃 适配 vscode-java-test 0.32.0 版本插件 #323 . @Ricbet 
  - [x] 支持测试资源管理器树形结构的数据更新 #324 
  - [x] 支持 Go To Test 的跳转 #326 
  - [x] 支持运行测试时的状态更新 #328
  - [x] 实现 Testing Decoration #335 
  - [x] 实现在 Testing Decoration 里运行测试用例 #336 
  - [x] 基于 ZoneWidget 之上实现了 PeekView Widget，简单实现了 Testing OutputPeek #351 
  - [x] 实现 Testing Message 内敛显示效果 #362 

## Terminal

- [x] 优化 terminal.type 设置项，使默认选项可以正常展示 #419 . @bytemain 
- [x]  支持 TerminalProfileProvider API #34. @bytemain 

## Preference

- [x] 设置面板支持自动根据配置项进行位置定位 #386 . @erha19 

## Task

- [x] fire task background begin and ended event #373 . @Aaaaash 
- [x] support process multi-line output in task #420

## Webview

- [x] 支持 Webview 根据 `ViewContainer` 变化控制展示或隐藏 #402 . @hacke2 

## Extension API

- [x] support `TaskGroup.isDefault / TaskGroup.id` property #76. @Aaaaash @ AhkunTa 

## QuickOpen

- [x] change quickopen eventEmitter to private property #406 . @hacke2 
- [x]  fix quicksearch possible infinite recursion #399 . @hacke2 

## Refactor

- [x] 👨🏻‍💻  use @opensumi/ide-components as sumi-browser's components #79. @erha19
- [x] 优化框架依赖结构 #110. @erha19 
- [x] 优化Remote Opener结构，去除core-browser耦合 @life2015  #431 

## Code Samples

- [x] 优化纯前端项目启动案例 #329. @ensorrow 

## Others

- [x] 修复 `Path.join` 工具方法无法处理 `./` 路径问题 #393 . @EAGzzyCSL 
- [x] 优化部分界面下文本不可选中状态 #385 . @sinoon 
- [x] upgrade marked and node-notifier for security #397 . @erha19 
- [x]  support remote opener contribution #379 . @Aaaaash 
- [x] support remote opener incorrect clientId fallback @life2015  #431 

## Style Change

- [x] 对齐文件树与右键菜单滚动条宽度 #368 . @erha19

**Comment by erha19** [comment]
- #453

**Comment by erha19** [comment]
正式版本已发布：[v2.15.0](https://github.com/opensumi/core/releases/tag/v2.15.0)
