### ISSUE TITLE
Iteration Plan for v2.16.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#605]
This plan captures our work in February. This is a 2-week iteration. We will ship in mid-February.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Roadmap

- [x] 2022 Roadmap [wiki/2022-Roadmap](https://github.com/opensumi/core/wiki/2022-Roadmap).

## Editor

- [x] 支持 `Go To Line` 命令 #569. @bytemain 
- [x] 修复编辑器自定义视图在插件重载后重复注册的问题 #534. @bk1012 
- [x] 修复编辑器显示切换按钮更新逻辑 #509. @Aaaaash 
- [x] 优化编辑器顶部面包屑样式 #599. @Aaaaash 

## FileTree

- [x] 优化文件树文件定位逻辑，防止打开大文件时带来的加载时序问题 #602. @erha19 

## Debug

- [ ] 🏃 适配 VS Code JavaScript Debugger 插件 1.62.0 版本 #396. @erha19 
- [x] 💪 调试控制台支持 ANSI 字符展示 #469. @Ricbet 

## Terminal

- [x] 使用用户 `Home` 目录作为终端默认目录 #550. @bytemain 

## Preference

- [x] 修复全局配置面板渲染异常问题 #548. @erha19 

## Toolbar

- [x] 修复 Toolbar 上 `popover ` 无法正常隐藏问题 #529. @EAGzzyCSL
- [x] 修复 Tabbar 拖拽图表样式问题 #520. @EAGzzyCSL

## Webview

- [x] 💪 在 `WebviewOptions` 中支持 `enableForm` 配置 #570. @AhkunTa 

## Extension API

- [x] 添加插件进程 `sumi` API 相关定义 #600. @bk1012 
- [x] 💪 支持在 `Worker API` 中使用 SCM API #596. @hacke2 
- [x] 💪 在 `FileStat` 中支持 `permission` 相关 API #561. @Ricbet 
- [x] 💪 支持 `vscode.OpenEditorInfo` API #539. @Ricbet 

## QuickOpen

- [x] 优化 `vscode.window.createInputBox` 接口表现 #591. @bytemain 
- [x] 修复 QuickPick 点击焦点问题 #584, #524. @hacke2 

## Refactor

- [x] 优化 `connect` 模块依赖引用结构 #551. @erha19 

## Code Style

- [x] 添加 `import` 校验规则，同时优化依赖排序 #552, #595. @EAGzzyCSL

## Tabbar

- [x] #556. @bytemain 

## Electron

- [x] 支持展示远程模式下的标题 #505. @yantze 

## Style Change

- [x] 优化编辑器和终端搜索框样式 #594. @Aaaaash 
- [x] 优化侧边栏边框样式 #589. @erha19 
- [x] 修复布局拖拽边缘样式 #585. @Aaaaash 
- [x] 优化部分编辑器组件样式 #571. @Aaaaash 
- [x]  优化部分弹窗阴影样式问题 #544. @Aaaaash 
- [x] 优化 `ErrorBoundary` 样式 #537. @erha19 
- [x] 优化编辑器文件加载样式 #526. @Aaaaash 

## Sample

- [x] 为项目示例添加自定义 `menubar` #525. @Aaaaash 

## Others

- [x] #597. @yantze 
- [x] #593. @erha19 
- [x] #587.  @winixt
- [x] #575. @Aaaaash 
- [x] #566. @Aaaaash 
- [x] #558. @erha19 
- [x] #536. @erha19 
- [x] #533. @Aaaaash 
- [x] #532. @bytemain 
- [x] #530. @Aaaaash 
- [x] #528. @erha19 
- [x] #522. @hacke2 
- [x] 优化更新日志生成逻辑 #516, #516, #513, #510, #506. @erha19 
- [x] #511. @Aaaaash 

## Typo

- [x] #603. @iamxukai
- [x] #590. @Ricbet 
- [x] #561. @iamxukai 
- [x] #554. @iamxukai 
- [x] #514. @erha19 

## Thanks

- @iamxukai
- @winixt

**Comment by erha19** [comment]
- #606

**Comment by bytemain** [comment]
这两天的新 commit 看起来还没有归纳进去。

**Comment by erha19** [comment]
> 这两天的新 commit 看起来还没有归纳进去。

回源 v2.15 相关的 PR ？如果有遗漏的话可以在这下面评论一下具体 PR

**Comment by erha19** [comment]
Web 版本测试回归：

- #618

**Comment by erha19** [comment]
Electron 版本测试回归：

- #637

**Comment by erha19** [comment]
New Version Released [v2.16.0](https://github.com/opensumi/core/releases/tag/v2.16.0).
