### ISSUE TITLE
Iteration Plan for v2.17.0

### ISSUE THREAD

**Issue by erha19** [opensumi/core#790]
This plan captures our work in February. This is a 3-week iteration. We will ship in mid-April.

# Plan Items

Legend of annotations:

|  Mark   | Description  |
|  ----  | ----  |
|🏃| work in progress |
|✋| blocked task |
|💪| stretch goal for this iteration |
|👨🏻‍💻| a large work item, larger than one iteration |
|🐚| under discussion within the team |

Below is a summary of the top-level plan items.

## Editor

- [x] 修复快速切换文件时的文件展示问题 #783. @AhkunTa  
- [x] 优化编辑器右键菜单样式 #749. @Aaaaash 
- [x] 编辑器响应文档变化前等待 hash 服务加载完成 #733. @MMhunter 
- [x] 支持更多的编辑器配置 #704. @bytemain 
- [x] 修复 `CMD+N` 创建新文件内容仍在新文件中展示的问题 #703. @hacke2 

## Extension Marketplace

- [ ] 💪 修复插件市场已安装插件仍搜索展示问题 #750. @erha19 

## FileTree

- [x] 优化文件树文件定位逻辑，防止打开大文件时带来的加载时序问题 #602. @erha19 
- [x] 优化文件树快照恢复逻辑，同时移除初始化阶段多余的刷新操作，解决首次加载闪烁问题 #776. @erha19 
- [x] 优化文件树对创建/删除文件等操作的响应速度 #736. @bytemain 
- [x] 优化快捷键操作下文件树焦点管理逻辑，让快捷键使用更顺滑 #714. @erha19 
- [x] 修复文件树多次刷新情况下概率出现编辑器文件无法在文件树下定位的问题 #709. @bytemain 
- [x] 支持空白处双击创建文件及 `CMD+A`全选节点的功能 #689. @bytemain 

## Debug

- [ ] 🏃 适配 VS Code JavaScript Debugger 插件 1.64.0 版本 #396. @erha19 
- [x] 💪 优化调试模式下按住 `Alt` 后 Hover 调试变量的交互  #773. @Ricbet 
- [x] 优化调试模式下，变量 Hover 的展示效果，使其不再被界面其他面板遮挡 #781. @Ricbet 

## Webview

- [x] 修复第二次打开 Webview 文件时空白的问题 #769. @Ricbet 

## Search

- [ ] 💪  优化搜索面板搜索速度及内容准确性 #765. @yantze 
- [ ] 优化搜索面板界面基础样式 #764. @yantze 
- [x] 搜索面板支持接收到输入后立即响应搜索能力 #737. @bytemain 
- [x] 解决已删除文件仍存在搜索结果中的问题 #691. @hacke2 

## Terminal

- [ ] 🏃 支持单/多容器架构下的终端重连能力 #713. @life2015 
- [x] 移动部分通用 Terminal 命令至 `COMMON_COMANDS` 中 #782. @bytemain 
- [x] 当无焦点情况下，自动聚焦最后一个终端面板 #762. @Aaaaash 
- [x] 终端 tab 支持滚动条展示 #761. @Aaaaash 
- [x] 使用 Pty 名称作为终端默认名称，同时支持图标展示 #732, #728. @Aaaaash 
- [x] 支持终端切换焦点快捷键 #724. @Aaaaash 
- [x] 终端字体无设置情况下默认使用编辑器中的字体 #697. @bytemain 
- [x] 支持更多终端打开入口 #686. @bytemain 

## Preference

- [ ] 修复默认配置对内联配置名，如 `a.b.c` 配置的支持 #763. @erha19 
- [x] 调整设置面板交互行为，添加部分额外配置，同时支持重载窗口时恢复配置 #720, #715. @bytemain 

## Keymaps

- [x] 修复快捷键面包搜索卡顿问题，同时支持清空搜索选项能力 #789. @erha19 

## Theme

- [x] 修复设置颜色/图标主题后刷新后仍有概率使用默认主题的问题 #775. @erha19 

## Connection

- [x] 升级 json-rpc 模块，解决容器部署环境下偶现的通信缓慢问题 #786. @Aaaaash 

## Webview

- [x] 💪 在 `WebviewOptions` 中支持 `enableForm` 配置 #570. @AhkunTa 
- [x] 修复 Electron 环境下，webview 可能重复加载两次的问题 #667. @MMhunter 

## StatusBar

- [x] StatusBar 面板展示的 Hover 信息支持 Markdown 展现 #758. @hacke2 

## Extension API

- [x] 实现 `workbench.action.openSettingsJson` 命令 #748. @Ricbet 
- [x] Progress Report 支持 Markdown 语法文本展示 #745. @Ricbet 
- [x] 修复 `vscode.env.appRoot` API 实现 #716. @erha19 

## QuickOpen

- [x] 修复 QuickPick 偶现的堆栈调用溢出问题 #753. @bytemain  
- [x] 修复 Electron 环境下 QuickPick 无法自动隐藏问题 #725. @bytemain 

## Refactor

- [ ]  🏃 整理框架 `utils` 工具，抽离 `@opensumi/ide-utils` 以获得更好的依赖结构，解决循环引用问题 #784. @erha19 
- [x] 移除框架中的 `lodash` 类库，所有工具方法均在 `lodash` 中引入，解决部分循环引用问题 #705. @erha19 
- [x] 重构编辑器中右键菜单的注入逻辑, 解决菜单功能准确性问题 #695. @Aaaaash 
- [x] ExtensionStorage 中移除 `crypto` 依赖，使用全局的 WASM Hash 服务，解决纯前端额外的 Polyfill 需求  #678. @bytemain
- [x] 移除插件进程中多余的 await 逻辑，加快整体框架启动速度 #668. @Aaaaash 

## Electron

- [x] 修复在 MacOS BigSur 及以上的编辑器窗口 Header 高度问题 #717. @yantze 
- [x] 修复 Electron 下 Connection 链接逻辑  #682. @bytemain 
- [x] 修复 Electron 下进程日志的捕获逻辑 #679. @bytemain 

## Storage

- [x] 优化 Storage 初始化逻辑，加快加载速度 #674. @Aaaaash 

## Style Change

- [x] 优化终端底部边框样式 #740. @Aaaaash 
- [x] 优化终端 Tab 样式 #722. @Aaaaash 
- [x] 优化终端加载中的样式展示 #708. @Aaaaash 

## Tabbar

- [x] 优化 Tabbar ResizeHandler 的加载时序，解决部分情况下可能出现的异常报错问题 #734. @bytemain 
- [x] ViewContainer 支持 icon 加载逻辑 #712. @Aaaaash 

## Sample

- [x] 为项目示例添加自定义 `menubar` #525. @Aaaaash 
- [x] 升级 Electron 项目默认 Electron 版本至 v13.6.9 #721. @yantze 
- [x] Remote 模式下使用 Web 版本 SaveDialog 作为存储文件面板 #669. @yantze 

## Others

- [x] #693. @MMhunter  
- [x] #687. @Aaaaash  
- [x] #681. @erha19 
- [x] #665. @bytemain 
- [x] 修复全局 Menu 子菜单展示问题 #755, #696. @Aaaaash 
- [x] 修改框架默认启动 HOST 为 `127.0.0.1` #760. @yantze 

Release Notes 见：[release-notes/v2.17.md](https://github.com/opensumi/doc/blob/main/release-notes/v2.17.md).

**Comment by erha19** [comment]
PreRelease #813.

**Comment by erha19** [comment]
Published [v2.17.0](https://github.com/opensumi/core/releases/tag/v2.17.0)
